variables:
  CONDITIONAL_BUILD_ANDROID_CTS_TAG: 2dfd3e288249e4776ef6866d34d344d4
  CONDITIONAL_BUILD_ANGLE_TAG: 663709da4e67bd523ff7fb39b1c40613
  CONDITIONAL_BUILD_CROSVM_TAG: 4c61f9707203afca91db3efeb57175db
  CONDITIONAL_BUILD_FLUSTER_TAG: e13f8521875ebd70e207ec0f6f3d3e5b
  CONDITIONAL_BUILD_PIGLIT_TAG: d027ff7015ba411736c1ac28a8663805
  CONDITIONAL_BUILD_VKD3D_PROTON_TAG: 051ea4f24ff300dd952dc7d43211a4f1
