[[fluster]]
bin = "/fluster/fluster.py"
decoders = [
  # "GStreamer-AV1-Vulkan-Gst1.0", # uncomment when updating to gstreamer >= 1.28
  # "GStreamer-VP9-Vulkan-Gst1.0", # uncomment when updating to gstreamer >= 1.28
  "GStreamer-H.264-Vulkan-Gst1.0",
  "GStreamer-H.265-Vulkan-Gst1.0",
]
